name: deploy prod

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Registry
        uses: docker/login-action@v2
        with:
          registry: https://registry.jh-research.de/v2/
          username: ${{ secrets.DOCKEREGISTRY_USER }}
          password: ${{ secrets.DOCKEREGISTRY_PASSWORD }}
      - name: Build and push - version
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: registry.jh-research.de/backend/afim-selector:${{ steps.date.outputs.date }}
      - name: Build and push - latest
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: registry.jh-research.de/backend/afim-selector:latest
